import numpy as np

rng = np.random.default_rng(seed=42)
y = rng.random((5,3))
print(y)



# random generations aren't actually random

# for cryptographic applications true random numbers are generated by 
# eg. hooking the computer up to a weak radioactive source

# Pi is random, no repetition

# seed refers to where in the sequence one start and allows to predict random generation (for decoding?)

# defining a seed allows to generate the same random data, security risk but allows to test code